---
- name: Install Node.js on Ubuntu
  hosts: web_servers
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present

    - name: Install npm package manager
      apt:
        name: npm
        state: present
